package com.quiz.web.MercQuizApp.service.utils;

import java.util.Date;

import org.springframework.beans.factory.config.ConfigurableBeanFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.S3Link;

/**
 * Data model class for an quiz stored in Amazon DynamoDB.
 */
@Component
@Scope(value = ConfigurableBeanFactory.SCOPE_PROTOTYPE)
@DynamoDBTable(tableName = "quiz")
public class Questions {

    private String id;
    private String quizName;
    private S3Link questionsLink;
    private Date creationTime;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public S3Link getQuestionsLink() {
        return questionsLink;
    }

    public void setQuestionsLink(S3Link startingImageLink) {
        this.questionsLink = startingImageLink;
    }

    public String getQuizName() {
        return quizName;
    }

    public void setQuizName(String topCaption) {
        this.quizName = topCaption;
    }

    public Date getCreationTime() {
        return creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
}
